name: learn-github
on: [push]
jobs:
  testing:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4.1.5
        - name: micromamba-setup
          uses: mamba-org/setup-micromamba@v1
          with:
            generate-run-shell: true
            environment-file: environment.yml
            cache-environment: true
        - name: build-and-install
          shell: micromamba-shell {0}
          run: |
            meson setup build
            pip install .
        - name: test
          run: | 
            pytest tests
